### ISSUE TITLE
 io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 2097152: 2894795278 - discarded

### ISSUE THREAD

**Issue by glcheng** [scalecube/scalecube-cluster#188]
After upgrading from 1.0.9 to 2.2.5 I'm getting these errors in the log. I disabled my code that does meta updates and sending messages/gossips. So the traffic is not generated by my code. What can be the cause of this?

2019-05-07 08:17:24 [sc-cluster-io-epoll-1] WARN   i.s.transport.ExceptionHandler - Exception caught for channel [id: 0x95fe7fbc, L:/10.5.XXX.XX:XXXX - R:/10.5.XXX.XX:48376], io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 2097152: 2894795278 - discarded
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 2097152: 2894795278 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:522)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failIfNecessary(LengthFieldBasedFrameDecoder.java:500)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.exceededFrameLength(LengthFieldBasedFrameDecoder.java:387)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:430)
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at java.lang.Thread.run(Thread.java:748)

**Comment by glcheng** [comment]
Additional errors when I enable the code that does meta data updes:

2019-05-07 08:25:36 [sc-cluster-8802-1] WARN   i.s.c.m.MetadataStoreImpl - Received GetMetadataReq: Message {headers: {q=sc/metadata/req, cid=86532ED58917A609FA61-1557217535253}, sender: 10.5.156.68:8802, data: GetMetadataRequest{member=1FDC2420E69DF37DECA9@10.5.156.92:8802}} to 1FDC2420E69DF37DECA9@10.5.XXX.XX:8802, but local member is C4D80416F23CAB2FCDC2@10.5.XXX.XX:8802
2019-05-07 08:25:36 [sc-cluster-8802-1] WARN   i.s.c.m.MetadataStoreImpl - Received GetMetadataReq: Message {headers: {q=sc/metadata/req, cid=9DC102173E98A015EDBB-1557217534867}, sender: 10.5.XXX.XX:8802, data: GetMetadataRequest{member=1FDC2420E69DF37DECA9@10.5.XXX.XX:8802}} to 1FDC2420E69DF37DECA9@10.5.XXX.XX:8802, but local member is C4D80416F23CAB2FCDC2@10.5.XXX.XX:8802
2019-05-07 08:25:36 [sc-cluster-8802-1] WARN   i.s.c.m.MetadataStoreImpl - Received GetMetadataReq: Message {headers: {q=sc/metadata/req, cid=C4D80416F23CAB2FCDC2-1557217535780}, sender: 10.5.XXX.XX:8802, data: GetMetadataRequest{member=1FDC2420E69DF37DECA9@10.5.XXX.XX:8802}} to 1FDC2420E69DF37DECA9@10.5.XXX.XX:8802, but local member is C4D80416F23CAB2FCDC2@10.5.XXX.XX:8802
2019-05-07 08:25:36 [sc-cluster-8802-1] ERROR  r.core.publisher.Operators - Operator called default onErrorDropped
java.lang.ClassCastException: io.scalecube.cluster.metadata.GetMetadataRequest cannot be cast to io.scalecube.cluster.metadata.GetMetadataResponse
        at io.scalecube.cluster.metadata.MetadataStoreImpl.lambda$null$0(MetadataStoreImpl.java:172)
        at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:137)
        at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:178)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-05-07 08:25:36 [sc-cluster-8802-1] ERROR  r.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
java.lang.ClassCastException: io.scalecube.cluster.metadata.GetMetadataRequest cannot be cast to io.scalecube.cluster.metadata.GetMetadataResponse
        at io.scalecube.cluster.metadata.MetadataStoreImpl.lambda$null$0(MetadataStoreImpl.java:172)
        at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:137)
        at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:178)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-05-07 08:25:36 [sc-cluster-8802-1] WARN   i.s.c.m.MetadataStoreImpl - Received GetMetadataReq: Message {headers: {q=sc/metadata/req, cid=C0D50EDECD6913C16F6C-1557217535738}, sender: 10.5.XXX.XX:8802, data: GetMetadataRequest{member=1FDC2420E69DF37DECA9@10.5.XXX.XX:8802}} to 1FDC2420E69DF37DECA9@10.5.XXX.XX:8802, but local member is C4D80416F23CAB2FCDC2@10.5.XXX.XX:8802
2019-05-07 08:25:39 [sc-cluster-8802-1] WARN   i.s.c.m.MetadataStoreImpl - Failed getting GetMetadataResp[C4D80416F23CAB2FCDC2-1557217535735] from 10.5.XXX.XX:8802 within 3000 ms, cause : java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 3000ms in 'source(MonoCreate)' (and no fallback has been configured)
2019-05-07 08:25:39 [sc-cluster-8802-1] WARN   i.s.c.m.MetadataStoreImpl - Failed getting GetMetadataResp[C4D80416F23CAB2FCDC2-1557217535736] from 10.5.XXX.XX:8802 within 3000 ms, cause : java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 3000ms in 'source(MonoCreate)' (and no fallback has been configured)

**Comment by artem-v** [comment]
This one is interesting

_
2019-05-07 08:25:36 [sc-cluster-8802-1] WARN i.s.c.m.MetadataStoreImpl - Received GetMetadataReq: Message {headers: {q=sc/metadata/req, cid=C4D80416F23CAB2FCDC2-1557217535780}, sender: 10.5.XXX.XX:8802, data: GetMetadataRequest{member=1FDC2420E69DF37DECA9@10.5.XXX.XX:8802}} to 1FDC2420E69DF37DECA9@10.5.XXX.XX:8802, but local member is C4D80416F23CAB2FCDC2@10.5.XXX.XX:8802
_

It tells that on member C4D80416F23CAB2FCDC2 it was possible to get request from C4D80416F23CAB2FCDC2 (attribute `cid` in message consists of  member-id plus counter)

**Comment by artem-v** [comment]
> 2019-05-07 08:25:36 [sc-cluster-8802-1] WARN i.s.c.m.MetadataStoreImpl - Received GetMetadataReq: Message {headers: {q=sc/metadata/req, cid=86532ED58917A609FA61-1557217535253}, sender: 10.5.156.68:8802, data: GetMetadataRequest{member=1FDC2420E69DF37DECA9@10.5.156.92:8802}} to 1FDC2420E69DF37DECA9@10.5.XXX.XX:8802, but local member is C4D80416F23CAB2FCDC2@10.5.XXX.XX:8802

86532ED58917A609FA61 issued request  on getting metadata from 1FDC2420E69DF37DECA9 , but the latter is already (prob. due to restart)  has different `member-id` which C4D80416F23CAB2FCDC2

**Comment by artem-v** [comment]
> java.lang.ClassCastException: io.scalecube.cluster.metadata.GetMetadataRequest cannot be cast to io.scalecube.cluster.metadata.GetMetadataResponse

This one is really bad. Looking into it.

**Comment by artem-v** [comment]
Issue with `io.netty.handler.codec.TooLongFrameException` is no longer reproduced, since `2.2.6`.  Make sure all nodes use the same version of `scalecube-cluster`.

**Comment by artem-v** [comment]
Upon `java.lang.ClassCastException: io.scalecube.cluster.metadata.GetMetadataRequest cannot be cast to io.scalecube.cluster.metadata.GetMetadataResponse`  -- this one is also wasn't reproduced (since `2.2.6`).

**Comment by artem-v** [comment]
Upon `... but local member is ...`  -- this is ok.

**Comment by artem-v** [comment]
@glcheng 
Upon my comment 
> Upon java.lang.ClassCastException: io.scalecube.cluster.metadata.GetMetadataRequest cannot be cast to io.scalecube.cluster.metadata.GetMetadataResponse -- this one is also not reproduced (since 2.2.6).

I managed to reproduce it. Created an issue -- #215.
