### ISSUE TITLE
After member restart getting ClassCastException

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-cluster#215]
```
2019-05-07 08:25:36 [sc-cluster-8802-1] ERROR r.core.publisher.Operators - Operator called default onErrorDropped
java.lang.ClassCastException: io.scalecube.cluster.metadata.GetMetadataRequest cannot be cast to io.scalecube.cluster.metadata.GetMetadataResponse
at io.scalecube.cluster.metadata.MetadataStoreImpl.lambda$null$0(MetadataStoreImpl.java:172)
at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:137)
at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:178)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

Reported at original issue #188 in [this comment]( https://github.com/scalecube/scalecube-cluster/issues/188#issuecomment-489986096)

**Comment by artem-v** [comment]
It's clear why-how-and-when this happens. Fix is on the way.
