### ISSUE TITLE
NPE at FailureDetector

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-cluster#220]
```
java.lang.NullPointerException: null
    at io.scalecube.cluster.fdetector.FailureDetectorImpl.computeMemberStatus(FailureDetectorImpl.java:376) ~[scalecube-cluster-2.3.1.jar:?]
    at io.scalecube.cluster.fdetector.FailureDetectorImpl.lambda$doPing$0(FailureDetectorImpl.java:153) ~[scalecube-cluster-2.3.1.jar:?]
    at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:137) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
    at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:178) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
    at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
    at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_212]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_212]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by artem-v** [comment]
False alarm. Reproduced only when nodes have different cluster  versions.
